### ISSUE TITLE
How to deserialize a JSON string to get ServerDrivenComponent manually?

### ISSUE THREAD

**Issue by hoangnv11** [ZupIT/beagle#1492] opened 2021-04-16 09:25 UTC
## Use case
I'm working on a cache solution in order to store Beagle Screen in JSON format locally on Android/iOS devices. Is there anyway enables me to manually deserialize JSON strings to get the ServerDrivenComponent?
Thank you!

**Comment by Tiagoperes** [comment] 2021-04-16 12:08
Hi @hoangnv11, Beagle already has native support for caching. It does does exactly that: https://docs.usebeagle.io/v1.6/resources/cache/overview/

I advice to first try to use the solution provided by the lib, if it doesn't get the job done, you can explain us what is missing and we can either improve the solution or tell you how to implement this yourself.

Unrelated: can you please check [this issue](https://github.com/ZupIT/beagle/issues/1490) for us, we could really use your help there.

**Comment by hoangnv11** [comment] 2021-04-16 14:11
> Hi @hoangnv11, Beagle already has native support for caching. It does does exactly that: https://docs.usebeagle.io/v1.6/resources/cache/overview/
> 
> I advice to first try to use the solution provided by the lib, if it doesn't get the job done, you can explain us what is missing and we can either improve the solution or tell you how to implement this yourself.
> 
> Unrelated: can you please check [this issue](https://github.com/ZupIT/beagle/issues/1490) for us, we could really use your help there.

Yeah I know Beagle already supports caching but I want to download all JSON snippets of all Beagle-based screen within our application at Splash Activity via an API call and store them locally, and then for each screen, we only need to read these files as string and render view using renderScreen() (for Android).

I've tested our solution as mentioned above and it worked, but now I'm stuck with overlapping Beagle fragments when I try to generate fragments along with bottom navigation view, as I describe in the issue #1491.

Therefore I'm thinking of deserializing the JSON by myself to get the server-driven component and then add it to the parent view on Android native using addView() method, but I don't know how to achieve it.

Hopefully you can help me with this problem @Tiagoperes

**Comment by hoangnv11** [comment] 2021-04-16 14:12
> Hi @hoangnv11, Beagle already has native support for caching. It does does exactly that: https://docs.usebeagle.io/v1.6/resources/cache/overview/
> 
> I advice to first try to use the solution provided by the lib, if it doesn't get the job done, you can explain us what is missing and we can either improve the solution or tell you how to implement this yourself.
> 
> Unrelated: can you please check [this issue](https://github.com/ZupIT/beagle/issues/1490) for us, we could really use your help there.

Upon the playground, I see that it's working for me. Thank you! :D

**Comment by Tiagoperes** [comment] 2021-04-16 15:35
Hmm, let me see if understood you correctly. Instead of loading the views on demand, you want to load everything at once in the splash screen? You will never need to load the JSON of a view after the splash screen?

It is possible to do what you want, you can parse a JSON string and create a screen. @uziasferreirazup will soon post an example for you. But I think we should first see if this is really what you want to do.

With this strategy, your navigations within a Beagle View won't work as intended. The action `beagle:pushView`, for instance, will try to load the view from the service anyway and completely bypass your local files. How are you intending to deal with this problem?

**If your application never ever makes a navigation inside a server driven view, then it's ok, it won't be a problem. But if it does, you'll have to create workarounds to fix this.**

Another way to think of your problem is: "how can I tell Beagle how to retrieve the Json of a view given a URL". The default behavior is to make a network call to the backend and return the Json, but you can change this and, instead, get the Json from some locally stored data. This is a more elegant solution to the problem and makes it so everything, including the navigation, works as any common use case for Beagle.

@uziasferreirazup will also give you an example of how to overwrite the default behavior of Beagle so you can retrieve the Json from some locally stored data instead of making a network request.

Observation: I don't write myself the examples because I'm not the right person to do so. I deal directly with Beagle Web and not really with Beagle Android. Since it's the same lib, despite the platform, I can help you coming up with the solution, but when it comes to coding, I prefer to ask people from the Android team to help.

**Comment by hoangnv11** [comment] 2021-04-16 17:24
Oh, it's very kind of you to have such a detailed comment as well as a thorough analysis. Many thanks! @Tiagoperes 
Yes that's right. You've understood my strategy I'm applying now.
I want to load everything at once in the splash screen and store them locally as .txt or .json files. Afterwards, I'll never have to load the JSON of a view from server anymore. If I make any changes to screen, I'll upgrade the JSON version in the database (I create a table to manage JSON versions of screens), then the client will automatically update the JSON of the screen which has been changed in the next time users open app (update at the splash screen).
That's what I've done so far.

Perhaps I'll just store JSON of several screens, there are still other Beagle screens I'll load view from server; moreover, I think I can manage navigations by creating custom navigation actions and pass into the corresponding JSON filename of the destination screen so that my app can know which local JSON file it should open to lod view. Therefore I think that navigation is not the problem, I can manage it 😬

The problem here is how can I deserialize a JSON string to get the component (a ServerDriventComponent object) by myself?
I know Beagle for Android provides the method renderScreen() to render a view using json string, but I used it and encountered the problem as I describe in the issue #1491, therefore I have to think of a way to deserialize json to get the component on my own.

@uziasferreirazup Can you help me with this problem?
Actually this issue is related to #1491, so if possible, can you read it and give me an idea to solve the problem? Sorry for this inconvenience but I really need it.
Thank you a million!
Thank you very much!

**Comment by Tiagoperes** [comment] 2021-04-16 19:57
Got it! Your strategy to deal with navigations with custom actions will work. But, we checked, and #1491 is indeed a bug. The fix for this will probably be available next friday, with the release of version 1.7.0.

With version 1.6.x you can only achieve this via the solution I previously suggested (by implementing a new HttpClient). It is a more complex solution, considering you won't be able to rely on the DefaultHttpClient any longer. But most of the code would be copy & paste.

If you wish, we can give you an example of how to replace the default http client with a custom one. Otherwise, I'll close this issue and keep you informed of our progress in #1491.

**Comment by hoangnv11** [comment] 2021-04-17 04:30
@Tiagoperes Excuse me, but I don't understand what you mean by these words "With version 1.6.x you can only achieve this via the solution I previously suggested (by implementing a new HttpClient)" 😅 What will I achieve?
Because while I'm waiting for the bug fixes in the version 1.7.0, I wish to deserialize JSON by myself to get the server-driven component.

Anyway, I'm also excited to see your example of how to use a custom HttpClient. I'm always willing to learn new things, and the way you implement something is always a good reference source for me :D 

Thank you!

**Comment by matheusribeirozup** [comment] 2021-04-19 15:52
Hi @hoangnv11 what @Tiagoperes meant is that with a custom HttpClient you solve your problem, as it uses in its core  `loadView` and consequently you would not need the `renderScreen` fix.

HttpClient in Beagle is an interface through which all requests made by Beagle go through, including those for the start of server driven flow or internal navigation, such as `pushView`. 

Having said all that, all you have to do is create a custom HttpClient and the moment you make the request, validate if the url references your local json (you can use the logic that is most convenient for you) and then decide whether to actually make the request http or return the local json. Here is an example:

```kotlin
const val LOCAL_PROTOCOL = "local://"

@BeagleComponent
class CustomClient : HttpClient {
    private fun loadLocalJson(
        request: RequestData,
        onSuccess: (responseData: ResponseData) -> Unit,
        onError: (responseData: ResponseData) -> Unit
    ): RequestCall {
        val viewName = request.uri.toString().removePrefix(LOCAL_PROTOCOL)

        try {
            val viewJson = JsonViewDatabase.getView(viewName)
            onSuccess(ResponseData(200, viewJson.toByteArray()))
        } catch (error: Error) {
            onError(ResponseData(404, error.toString().toByteArray()))
        }

        return object: RequestCall {
            override fun cancel() {}
        }
    }

    private fun executeHttpRequest(
        request: RequestData,
        onSuccess: (responseData: ResponseData) -> Unit,
        onError: (responseData: ResponseData) -> Unit
    ): RequestCall {
        val requestBuilder = Request.Builder().url(request.uri.toString())

        addMethod(request, requestBuilder)
        addHeaders(request.headers, requestBuilder)

        val httpClient = OkHttpClient.Builder()

        httpClient.addInterceptor(object : Interceptor {
            override fun intercept(chain: Interceptor.Chain): Response {
                val newRequest = chain.request().newBuilder()
                    .header("KEY", "VALUE")
                    .build()

                return chain.proceed(newRequest)
            }
        })

        val requestCall = httpClient.build().newCall(requestBuilder.build())
        requestCall.enqueue(object: Callback {
            override fun onFailure(call: Call, e: IOException) {
                throw e
            }

            override fun onResponse(call: Call, response: Response) {
                if (response.isSuccessful
                    || response.code == 304) { // Treatment for HttpURLConnection.HTTP_NOT_MODIFIED
                    onSuccess(createResponseData(response))
                } else {
                    onError(createResponseData(response))
                }
            }
        })

        return object: RequestCall {
            override fun cancel() {
                requestCall.cancel()
            }
        }
    }

    override fun execute(
        request: RequestData,
        onSuccess: (responseData: ResponseData) -> Unit,
        onError: (responseData: ResponseData) -> Unit
    ): RequestCall {
        val isLocalRequest = request.uri.toString().startsWith(LOCAL_PROTOCOL)
        return (
            if (isLocalRequest) loadLocalJson(request, onSuccess, onError)
            else executeHttpRequest(request, onSuccess, onError)
        )
    }

    private fun createResponseData(response: Response): ResponseData {
        val body = response.body?.bytes() ?: byteArrayOf()
        val headers = mutableMapOf<String, String>()
        (0 until response.headers.size).forEach {
            val headerName = response.headers.name(it)
            val headerValue = response.headers.value(it)
            headers[headerName] = headerValue
        }
        return ResponseData(response.code, body, headers)
    }

    private fun addHeaders(headers: Map<String, String>, requestBuilder: Request.Builder) {
        headers.forEach {
            requestBuilder.addHeader(it.key, it.value)
        }
    }

    private fun addMethod(requestData: RequestData, requestBuilder: Request.Builder) {
        when (requestData.method) {
            HttpMethod.GET -> requestBuilder.get()
            HttpMethod.POST -> requestBuilder.post(createRequestBody(requestData.body))
            HttpMethod.DELETE -> requestBuilder.delete()
            HttpMethod.PUT -> requestBuilder.put(createRequestBody(requestData.body))
            HttpMethod.PATCH -> requestBuilder.patch(createRequestBody(requestData.body))
            HttpMethod.HEAD -> requestBuilder.head()
        }
    }

    private fun createRequestBody(body: String?): RequestBody {
        val contentType = "application/json; charset=utf-8".toMediaTypeOrNull()
        val bodyValue = body ?: ""
        return bodyValue.toRequestBody(contentType)
    }
}
```

Don't be scared by all this code, a good part of it was copied from the [default http client](https://github.com/ZupIT/beagle-helpers/blob/main/android/beagle-defaults/src/main/java/br/com/zup/beagle/defaults/httpclient/HttpClientDefault.kt), implemented in the beagle helpers lib.

In any case, I already opened the PR that corrects the [renderScreen bug](https://github.com/ZupIT/beagle/issues/1491) and in version 1.7.0 it will be ok.

**Comment by hoangnv11** [comment] 2021-04-19 16:57
Oh finally I see your point as well as @Tiagoperes's.
I'll try using custom HttpClient as the example you provide above tomorrow morning.
Thank you very much for your help!

And how about the version 1.7.0? I'm curious to know when will it be released? @matheusribeirozup

**Comment by matheusribeirozup** [comment] 2021-04-19 18:17
Hi @hoangnv11 we are scheduled to launch until Friday the 1.7.0, however if there is any unforeseen this date may not be reached. Until then, if you have any doubts, just call us again :).

**Closed** 2021-04-23 21:08 UTC
