### ISSUE TITLE
[Android] Screen transition is presenting some glitches

### ISSUE THREAD

**Issue by othiagosouto** [ZupIT/beagle#839] opened 2020-08-27 14:18 UTC
## Description
We're doing some navigation through our app and we've noticed that some glitches were presented.

## Steps To Reproduce

1. Open sobre server driven screen
2. Click on some button that will start another server-driven screen

## Expected Results
Some soft transitions should be presented.

## Code example, screenshot, or link to a repository:
We got this error
```
E/FragmentManager: No field with the name mListener is found in Animation class
    java.lang.NoSuchFieldException: No field mListener in class Landroid/view/animation/Animation; (declaration of 'android.view.animation.Animation' appears in /system/framework/framework.jar!classes3.dex)
        at java.lang.Class.getDeclaredField(Native Method)
        at android.support.v4.app.FragmentManagerImpl.getAnimationListener(FragmentManager.java:1301)
        at android.support.v4.app.FragmentManagerImpl.animateRemoveFragment(FragmentManager.java:1638)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1548)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```

**Comment by paulomeurerzup** [comment] 2020-08-28 13:11
![beagle_bug_839](https://user-images.githubusercontent.com/66129650/91564206-a54c1300-e916-11ea-8f3b-50142246668c.gif)

**Comment by gabrielleonardozup** [comment] 2020-09-01 19:55
Hi @othiagosouto, we investigated this problem and  executed a similar flow in android emulador with API 19, API 27 and API 29, all of them using Beagle with support version ( Beagle 1.1.0 ) and we were unable to reproduce the animation error.

But we discovered something, even though the transition animation hasn't bugged, there is one situation that reproduces the exception that you provided us, running the project using support version with API 29. This is a known bug of android fragment and was fixed in newer version of androidx, but apparently the fix was not implemented in support library.

So, we would like to suggest the following: Could you please try to run your app in an emulator with API lower than 29 and see if this error occurs? And also try to use Beagle without support version ( hosting in MavenCentral ) and also see if this error occurs?

Why are we suggesting that? Because we tried here and no exception was thrown for this cases. So apparently this only occurs in API 29 with support library. 

Here is the link to animation issuer tracking:
[https://issuetracker.google.com/issues/139349998](url)

**Comment by othiagosouto** [comment] 2020-09-01 20:08
We could try do this: "Could you please try to run your app in an emulator with API lower than 29 and see if this error occurs?" but unfortunately we can't migrate to AndroidX right now and we don't have any prevision about that.

If this is a bug on android-support, are you saying that there's no fix or workaround for that?

**Comment by othiagosouto** [comment] 2020-09-01 20:59
@gabrielhaddadzup

**Comment by gabrielleonardozup** [comment] 2020-09-24 19:04
Hi @othiagosouto , we changed some internal behaviors and you can use some states in onServerDrivenContainerStateChanged() method inside your beagleActivity to handle your toolbar visibility, like the following sample:

```
override fun onServerDrivenContainerStateChanged(state: ServerDrivenState) {
        if (state is ServerDrivenState.Started) {
            mToolbar.visibility = View.GONE
        } else if((state is ServerDrivenState.Success) || (state is ServerDrivenState.Finished)) {
            mToolbar.visibility = View.VISIBLE
        }
    }
```

**Closed** 2020-10-09 14:01 UTC
Labels: android, bug
