### ISSUE TITLE
Add option to execute list of actions one after the other, instead of in parallel asynchronously

### ISSUE THREAD

**Issue by vitor-ramos** [ZupIT/beagle#750] opened 2020-08-12 14:38 UTC
## Use case

In my chat app, when the user sends a message, the string goes from the context to a history using a custom action, them, I use SetContext to clear the TextInput. But because the code runs asynchronously, the context is cleare before my action can save the text in the history.

To solve my problem, I asked for an onComplete Action in my custom action, so I can execute it after my code runs properly. But I imagine we will have cases where a list of several actions needs to run one after the other, and using the onComplete approach would be a lot messy.

## Proposal

We could have a parameter to indicate that we want the list to run synchronously (Button as an example):

```
data class Button(
    val text: Bind<String>,
    val styleId: String? = null,
    val onPress: List<Action>? = null,
    val runSynchronously: Boolean = false, // <- New parameter here
    val clickAnalyticsEvent: ClickEvent? = null
)
```

Maybe instead of needing to add 2 parameters everywhere we have a list of actions, we can have a Class with both parameters:

```
data class ActionsList(val actions: List<Action>, val runSynchronously: Boolean = false)
```

And use it like this:

```
data class Button(
    val text: Bind<String>,
    val styleId: String? = null,
    val onPress: ActionsList? = null, // <- ActionsList here
    val clickAnalyticsEvent: ClickEvent? = null
)
```

**Comment by paulomeurerzup** [comment] 2020-08-18 19:03
Maybe we could use chain of responsibility pattern and create an ActionHandler?

https://refactoring.guru/pt-br/design-patterns/chain-of-responsibility

**Comment by Tiagoperes** [comment] 2020-08-19 12:29
Hi, the array of actions was designed to act like this. The next action in the array should never wait the previous action to finish before it starts. If you need an action to run after another, you should use nested actions instead. See the example of the action `beagle:sendRequest`:

```json
{
  "_beagleAction_": "beagle:sendRequest",
  "url": "https://mybackend.com/resource",
  "onSuccess": [{
    "_beagleAction_": "beagle:alert",
    "message": "done"
  }]
}
```

Since the `sendRequest` is an async operation and we need the alert to be executed only after the request finishes, the alert is specified as a property of the sendRequest.

In your use case, your custom action to save something in the history should have an `onFinish` property and the `setContext` to clear the context should be placed as the value of this property. Example:

```json
{
  "_beagleAction_": "custom:saveHistory",
  "value": "@{myContext}",
  "onFinish": [{
    "_beagleAction_": "beagle:setContext",
    "id": "myContext",
    "value": {}
  }]
}
```

**Comment by tuliopereirazup** [comment] 2020-08-19 13:20
On Android specifically you could use coroutines to dispatch your code to another thread and later on execute the success/error actions.

**Comment by uziasferreirazup** [comment] 2021-03-02 17:12
at this point we decided to close this issue, as we have no plans yet to add something that provides by default in the core, if you feel the need we can make an example together of how to solve this problem.

**Closed by uziasferreirazup** 2021-03-02 17:12 UTC
