### ISSUE TITLE
Image doesn't show placeholder image

### ISSUE THREAD

**Issue by minmon98** [ZupIT/beagle#1568] opened 2021-05-18 01:47 UTC
I have a remote image but sometimes the url is wrong or it takes a long time to load the image, so I set a placeholder image to show on screen in case of timeout. It does show but immediately hide then

<img width="496" alt="Screen Shot 2021-05-18 at 08 39 36" src="https://user-images.githubusercontent.com/40994028/118577967-8697f000-b7b5-11eb-8c6f-0f8565142eaf.png">
<img width="1183" alt="Screen Shot 2021-05-18 at 08 42 21" src="https://user-images.githubusercontent.com/40994028/118577972-88fa4a00-b7b5-11eb-8c36-2d5406d87e0c.png">

![video](https://user-images.githubusercontent.com/40994028/118603833-9d9f0800-b7de-11eb-88b5-efb130d3a49e.gif)

Could you check it for me, please. Thank you

**Comment by minmon98** [comment] 2021-05-19 07:02
@Tiagoperes sorry for my lack information, my issue is happended on iOS

**Comment by Tiagoperes** [comment] 2021-05-19 11:48
Oh, I assumed it was on Android. Since @matheusribeirozup did open a PR to fix this, this problem probably happens on both platforms.

I'll ask someone from the iOS team to check it for us, thanks for clarifying.

**Comment by matheusribeirozup** [comment] 2021-05-19 13:06
Hi @minmon98 , can you provide more context about this error? Is the `Image` component inside a `ListView`, or a `Container` for example? More information is needed because coincidentally I found this error on Android but we were unable to reproduce on iOS.

**Comment by minmon98** [comment] 2021-05-25 01:59
@matheusrcostazup I put Image in a Container and it is the template of a gridview I created before by myself

**Comment by matheusribeirozup** [comment] 2021-05-25 12:12
Yeah, we still can't reproduce your error. Can you send us the code for this screen and components? Both BFF and iOS, if you prefer to do this in private, you can send me in my email **matheusribeirolima@gmail.com**.

**Comment by matheusribeirozup** [comment] 2021-06-14 18:40
I'm going to close this issue now, since on Android it was fixed and it was not possible to reproduce the same scenario on iOS.

**Closed by matheusribeirozup** 2021-06-14 18:40 UTC
Labels: android, bug, iOS
